language: node_js
cache: yarn
node_js:
  - "8"

env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script: yarn test && codecov

notifications:
  email: false
