language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "8"

env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
after_success: npm run coverage

notifications:
  email: false
