# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "packages/client/dist/"
  command = "yarn workspace k-app-client run build:prod"

[build.environment]
  NODE_VERSION = "12"

[context.deploy-preview]
  command = "yarn workspace k-app-client run build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
