// This file is automatically generated by inject.env.js script
/* tslint:disable */
export const environment = {
  production: true,
  RECAPTCHA_SITE_KEY: undefined,
  BUGSNAG_KEY: undefined,
  API_HOSTNAME: "",
  JWT_DAY_EXP_LONG: 30,
  JWT_DAY_EXP: 1,
};
