// This file is automatically generated by git.version.js script
export const versions = {
  repo: 'https://github.com/K-Fet/K-App',
  version: '2.3.5',
  revision: '65ebfa9',
  branch: 'master',
  buildDate: 1563873748419,
};
