const { writeFileSync } = require('fs');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

const pkg = require('../package');
const rootPkg = require('../../../package');

async function createVersionsFile(filename) {
  const revision = (await exec('git rev-parse --short HEAD')).stdout.toString().trim();
  const branch = (await exec('git rev-parse --abbrev-ref HEAD')).stdout.toString().trim();

  console.log(`version: '${pkg.version}', revision: '${revision}', branch: '${branch}'`);

  const content = `// This file is automatically generated by git.version.js script
export const versions = {
  repo: '${rootPkg.repository.url}',
  version: '${pkg.version}',
  revision: '${revision}',
  branch: '${branch}',
  buildDate: ${Date.now()},
};
`;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('src/environments/versions.ts');
