// This file is automatically generated by git.version.js script
export const versions = {
  repo: 'https://github.com/K-Fet/K-App',
  version: '2.1.3',
  revision: '0c3b71b',
  branch: 'angular-upgrade',
};
