on: push
name: Test All
jobs:
  yarnInstallFront:
    name: Yarn install front
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Yarn install front
      uses: Borales/actions-yarn@master
      with:
        args: install --cwd client --frozen-lockfile
    - name: Yarn install back
      uses: Borales/actions-yarn@master
      with:
        args: install --frozen-lockfile
    - name: Yarn test
      uses: Borales/actions-yarn@master
      with:
        args: test
    - name: Trigger prod workflow
      uses: swinton/httpie.action@8ab0a0e926d091e0444fcacd5eb679d2e2d4ab3d
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        args: --auth-type=jwt --auth=$PAT_TOKEN POST api.github.com/repos/${{ github.repository
          }}/dispatches Accept:application/vnd.github.everest-preview+json event_type=deploy-prod
    - name: Trigger staging workflow
      uses: swinton/httpie.action@8ab0a0e926d091e0444fcacd5eb679d2e2d4ab3d
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        args: --auth-type=jwt --auth=$PAT_TOKEN POST api.github.com/repos/${{ github.repository
          }}/dispatches Accept:application/vnd.github.everest-preview+json event_type=deploy-master
