on: release
name: Update prod branch on release
jobs:
  updateBranch:
    name: Update branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update branch
      uses: Embraser01/update-git-branch-action@master
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        args: --branch prod --force
