on: repository_dispatch
name: Call prod webhook
jobs:
  filterProd:
    name: Filter prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter prod
      uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
      with:
        args: branch prod
    - name: Filter prod branch
      uses: actions/bin/filter@master
      with:
        args: action deploy-prod
    - name: Send prod webhook
      uses: swinton/httpie.action@master
      env:
        KAPP_WEBHOOK_TOKEN: ${{ secrets.KAPP_WEBHOOK_TOKEN }}
        KAPP_WEBHOOK_URL: https://webhooks.kfet-insa.fr
      with:
        args: POST $KAPP_WEBHOOK_URL action=deploy-prod token=$KAPP_WEBHOOK_TOKEN
          sha=${{ github.sha }}
